#!/bin/bash
# tary, 18:03 2018/7/24

# set -x

DEV_DIR="/sys/class/net"

[ "$#" -eq 0 -o "$1" == "-h" -o "$1" == "--help" ] && {
	echo "Usage"
	echo "  $0 can0,can1 can1,can2 ...";
	exit 1;
}

#display_fifo=${TMPDIR:-"/tmp"}/common_test_fifo
#display_cpuinfo='0'
display_echo=
display_result=

display_message() {
	local msg="$1$2"
	# echo $msg > $display_fifo
	echo $msg
}

field_get() {
	local delim=$1
	local line=$2
	local index=$3

	set `echo $line | tr \'$delim\' ' '`
	eval val=\$$index
	echo $val
}

connection_test() {
	local out=$1
	local in=$2
	local v
	local f

	# message 1122334455667788
	f=$(mktemp)
	candump $in > $f &
	sleep 0.5
	cansend $out 111#1122334455667788
	sleep 0.5

	v=$(cat $f)
	kill -9 $!
	wait
	echo "Recv '$v'" >&2
	rm -f $f

	f=$(expr index "$v" "111   [8]  11 22 33 44 55 66 77 88")
	[ "$f" -eq 0 ] && { return 1; }

# quick path
return 0

	# mesage 1234567890ABCDEF
	f=$(mktemp)
	candump $in > $f &
	sleep 0.5
	cansend $out 123#1234567890ABCDEF
	sleep 0.5

	kill -9 $!
	wait
	v=$(cat $f)
	echo "Recv '$v'" >&2
	rm -f $f

	f=$(expr index "$v" "123   [8]  12 34 56 78 90 AB CD EF")
	[ "$f" -eq 0 ] && { return 1; }

	return 0;
}

dev_setup() {
	ip link set can0 donw
	sleep 0.1
	ip link set can0 type can bitrate 500000
	sleep 0.1
	ip link set can0 up
	return
}

pairs_test() {
	local da=$1
	local db=$2
	local ers="$da,$db "

	[ ! -e $DEV_DIR/$da -o ! -e $DEV_DIR/$db ] && {
		echo -ne "$ers"
		return 1;
	}

	dev_setup $da
	dev_setup $db

	connection_test $da $db || {
		echo -ne "$ers"
		return 1;
	}

	# return 0;

	#connection_test $db $da || {
	#	echo -ne "$ers"
	#	return 1;
	#}
	return 0;
}

LAST_DIR=`pwd`
error_groups=""

for i in $@; do
	deva=$(field_get ',' $i 1)
	devb=$(field_get ',' $i 2)
	# echo DEVA=$deva DEVB=$devb

	error_groups="${error_groups}$(pairs_test $deva $devb)"
	[ "X$error_groups" != "X" ] && {
		true # display_message $display_result "$error_groups"
	}
done

# echo "#error groups = '${error_groups}'"

[ "X$error_groups" != "X" ] && {
	display_message $display_result "$error_groups"
	# sleep 5
	exit 1;
}

echo "$0: Version CAN"
display_message $display_echo " OK"
cd $LAST_DIR
exit 0
