#!/bin/bash

#mount /dev/sda1 /mnt/
#cd /mnt/
while [ 1 ]
do
	mount /dev/sda1 /mnt/
	r=$?
	if [ $r -eq 0 ]; then
		cd /mnt/
		dd if=/dev/zero of=usb_test bs=1M count=10 && { gpio set 50; sleep 0.5; gpio clear 50; }
		cd /root/
		umount /dev/sda1
	fi
	sleep 0.1
done
